#!/usr/bin/env python

Import("env")

env.modules_files = []

SConscript("math/SCsub")
SConscript("graphics/SCsub")
SConscript("viewport/SCsub")
SConscript("audio/SCsub")
SConscript("keyboard/SCsub")
SConscript("mouse/SCsub")