#!/usr/bin/env python

Import("env")

env.core_files = [
    "src/core.cpp",
    "src/engine.cpp",
    "src/events.cpp",
]

SConscript("math/SCsub")
SConscript("viewport/SCsub")
SConscript("graphics/SCsub")
SConscript("audio/SCsub")